services:
  app:
    build: .
    container_name: honeypot_scanner
    restart: unless-stopped
    volumes:
      - ./reports:/app/reports
    ports:
      - "2222:2222"
      - "8000:8000"
      - "5000:5000"
