services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.dev

  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/workspace
      - sepa_keys:/workspace/keys
    env_file:
      - .env.dev
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email your@email.com --agree-tos --no-eff-email
      -d yourdomain.com"

volumes:
  postgres_data:
  sepa_keys:
