# Generated by Django 5.2.3 on 2025-06-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gpt4", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="oauth_state",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]