# Generated by Django 5.2 on 2025-05-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtransferencia',
            name='tipo_log',
            field=models.CharField(choices=[('AUTH', 'Autenticación'), ('TRANSFER', 'Transferencia'), ('XML', 'Generación XML'), ('AML', 'Generación AML'), ('ERROR', 'Error'), ('SCA', 'Autenticación fuerte'), ('OTP', 'Generación OTP')], max_length=20),
        ),
    ]
