name: devcontainer_ant

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    restart: unless-stopped
    init: true
    depends_on:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftapi4_ant
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped
    init: true
    depends_on:
      - backend
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftapi4_ant
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - mode: ingress
        target: 5432
        published: "5434" # Cambiado de 5433 a 5434 para evitar conflictos
        protocol: tcp    
volumes:
  db_data:
    driver: local
networks:
  default:
    driver: bridge