version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ghostdb
      POSTGRES_USER: ghostuser
      POSTGRES_PASSWORD: ghostpass

volumes:
  postgres_data:
