# Generated by Django 5.2 on 2025-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entorno', models.CharField(choices=[('production', 'Producción'), ('sandbox', 'Sandbox'), ('local', 'Local')], default='production', max_length=20)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración API',
                'verbose_name_plural': 'Configuraciones API',
                'db_table': 'configuraciones_api',
            },
        ),
    ]
