name: devcontainer_ant3
services:
  app:  
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    restart: always
    init: true
    depends_on:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftapi4_ant3
      DATABASE_URL: postgres://postgres:postgres@database:5432/swiftapi4_ant3
    networks:
      - app_network
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swiftapi4_ant3
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - mode: ingress
        target: 5432
        published: "5436" # Cambiado de 5433 a 5434 para evitar conflictos
        protocol: tcp    
    networks:
      - app_network
volumes:
  db_data:
    driver: local
networks:
  app_network:
    driver: bridge