version: '3.9'
services:
  app:
    build: .
    container_name: simulador_staging
    ports:
      - '9181:8000'
    env_file:
      - .env.staging
    volumes:
      - .:/app
    command: gunicorn -c config/gunicorn_staging.conf.py simulador_banco.wsgi:application

  tor:
    image: goldy/tor-hidden-service
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: 127.0.0.1
    volumes:
      - ./torrc_staging:/etc/tor/torrc
      - ./tor_data_staging:/var/lib/tor
